<?php
$arr=array(1,"black",true);
$arr1=["red",21,false];
$arr[4]="pink";
$var1=$arr[1];
echo($var1);
echo "<br> pop()<br>";
$arr2=$arr;
array_pop($arr2);
print_r($arr2);
echo"<br> push() <br>";
array_push($arr2,"as",8);
print_r($arr2);echo"<br>";
echo"<br> shift()<br>";
array_shift($arr2);
print_r($arr2);
echo"<br> Unshift() <br>";
array_unshift($arr2,"first","second");
print_r($arr2);echo"<br>";
$arr4=[2,63,42,76,11];
sort($arr4);
echo"<br> Sort: <br>";
print_r($arr4);
echo"<br> Reverse Sort: <br>";
rsort($arr4);
print_r($arr4);
$arr3=array_slice($arr2,3,4);echo"<br>";
echo"<br> Original :<br>";
print_r($arr2);echo"<br>";
echo"<br> Slice :";
print_r($arr3);echo"<br>";
$mer_arr=array_merge($arr3,$arr);
echo"<br> Merge Array: <br>";
print_r($mer_arr);
$str=implode(",",$arr3);
var_dump($str);
echo"<br> String To Array: <br>";
$ex_arr=explode("e",$str);
print_r($ex_arr);echo"<br>";
$arr=[1,7,3,9,73,9,4,2];
$arr_uni=array_unique($arr);
print_r($arr_uni);
?>
